//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int IdEntrega { get; set; }
        public Nullable<int> IdPaquete { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> IdEstatusEntrega { get; set; }
    
        public virtual EstatusEntrega EstatusEntrega { get; set; }
        public virtual Paquete Paquete { get; set; }
        public virtual Repartidor Repartidor { get; set; }
    }
}
