//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JGarciaTrakingAndTraceEntities : DbContext
    {
        public JGarciaTrakingAndTraceEntities()
            : base("name=JGarciaTrakingAndTraceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entrega> Entregas { get; set; }
        public virtual DbSet<EstatusEntrega> EstatusEntregas { get; set; }
        public virtual DbSet<EstatusUnidad> EstatusUnidads { get; set; }
        public virtual DbSet<Paquete> Paquetes { get; set; }
        public virtual DbSet<Repartidor> Repartidors { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UnidadEntrega> UnidadEntregas { get; set; }
    
        public virtual int DeleteUsuario(Nullable<int> idusuario)
        {
            var idusuarioParameter = idusuario.HasValue ?
                new ObjectParameter("idusuario", idusuario) :
                new ObjectParameter("idusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUsuario", idusuarioParameter);
        }
    
        public virtual ObjectResult<GetAllUsuario_Result> GetAllUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUsuario_Result>("GetAllUsuario");
        }
    
        public virtual int UpdateUsuario(Nullable<int> idUsuario, string username, byte[] password, Nullable<int> idrol, string email, string nombre, string apellidoP, string apellidoM)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(byte[]));
    
            var idrolParameter = idrol.HasValue ?
                new ObjectParameter("idrol", idrol) :
                new ObjectParameter("idrol", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoPParameter = apellidoP != null ?
                new ObjectParameter("apellidoP", apellidoP) :
                new ObjectParameter("apellidoP", typeof(string));
    
            var apellidoMParameter = apellidoM != null ?
                new ObjectParameter("apellidoM", apellidoM) :
                new ObjectParameter("apellidoM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUsuario", idUsuarioParameter, usernameParameter, passwordParameter, idrolParameter, emailParameter, nombreParameter, apellidoPParameter, apellidoMParameter);
        }
    
        public virtual int UsuarioAdd(string username, byte[] password, Nullable<int> idrol, string email, string nombre, string apellidoP, string apellidoM)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(byte[]));
    
            var idrolParameter = idrol.HasValue ?
                new ObjectParameter("idrol", idrol) :
                new ObjectParameter("idrol", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoPParameter = apellidoP != null ?
                new ObjectParameter("apellidoP", apellidoP) :
                new ObjectParameter("apellidoP", typeof(string));
    
            var apellidoMParameter = apellidoM != null ?
                new ObjectParameter("apellidoM", apellidoM) :
                new ObjectParameter("apellidoM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UsuarioAdd", usernameParameter, passwordParameter, idrolParameter, emailParameter, nombreParameter, apellidoPParameter, apellidoMParameter);
        }
    
        public virtual ObjectResult<GetAllRol_Result> GetAllRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllRol_Result>("GetAllRol");
        }
    
        public virtual ObjectResult<GetByEmailUsuario_Result> GetByEmailUsuario(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByEmailUsuario_Result>("GetByEmailUsuario", emailParameter);
        }
    
        public virtual ObjectResult<GetByIdUsuario_Result> GetByIdUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdUsuario_Result>("GetByIdUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<GetAllEstatusUnidad_Result> GetAllEstatusUnidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllEstatusUnidad_Result>("GetAllEstatusUnidad");
        }
    
        public virtual ObjectResult<GetAllUnidadAsignada_Result> GetAllUnidadAsignada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUnidadAsignada_Result>("GetAllUnidadAsignada");
        }
    
        public virtual int PaqueteDelete(Nullable<int> idPaquete)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("idPaquete", idPaquete) :
                new ObjectParameter("idPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteDelete", idPaqueteParameter);
        }
    
        public virtual ObjectResult<PaqueteGetAll_Result> PaqueteGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaqueteGetAll_Result>("PaqueteGetAll");
        }
    
        public virtual ObjectResult<PaqueteGetById_Result> PaqueteGetById(Nullable<int> idPaquete)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("idPaquete", idPaquete) :
                new ObjectParameter("idPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaqueteGetById_Result>("PaqueteGetById", idPaqueteParameter);
        }
    
        public virtual int PaqueteUpdate(Nullable<int> idPaquete, string detalle, Nullable<double> peso, string direccionOrigen, string direccionEntrega, Nullable<System.DateTime> fecha, string codigoRastreo)
        {
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("idPaquete", idPaquete) :
                new ObjectParameter("idPaquete", typeof(int));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(double));
    
            var direccionOrigenParameter = direccionOrigen != null ?
                new ObjectParameter("direccionOrigen", direccionOrigen) :
                new ObjectParameter("direccionOrigen", typeof(string));
    
            var direccionEntregaParameter = direccionEntrega != null ?
                new ObjectParameter("direccionEntrega", direccionEntrega) :
                new ObjectParameter("direccionEntrega", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var codigoRastreoParameter = codigoRastreo != null ?
                new ObjectParameter("codigoRastreo", codigoRastreo) :
                new ObjectParameter("codigoRastreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteUpdate", idPaqueteParameter, detalleParameter, pesoParameter, direccionOrigenParameter, direccionEntregaParameter, fechaParameter, codigoRastreoParameter);
        }
    
        public virtual ObjectResult<SeguimientoPaquete_Result> SeguimientoPaquete(string codigoRastreo)
        {
            var codigoRastreoParameter = codigoRastreo != null ?
                new ObjectParameter("codigoRastreo", codigoRastreo) :
                new ObjectParameter("codigoRastreo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SeguimientoPaquete_Result>("SeguimientoPaquete", codigoRastreoParameter);
        }
    
        public virtual int PaqueteAdd(string detalle, Nullable<double> peso, string direccionOrigen, string direccionEntrega)
        {
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(double));
    
            var direccionOrigenParameter = direccionOrigen != null ?
                new ObjectParameter("direccionOrigen", direccionOrigen) :
                new ObjectParameter("direccionOrigen", typeof(string));
    
            var direccionEntregaParameter = direccionEntrega != null ?
                new ObjectParameter("direccionEntrega", direccionEntrega) :
                new ObjectParameter("direccionEntrega", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaqueteAdd", detalleParameter, pesoParameter, direccionOrigenParameter, direccionEntregaParameter);
        }
    
        public virtual ObjectResult<UltimoAñadido_Result> UltimoAñadido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UltimoAñadido_Result>("UltimoAñadido");
        }
    }
}
